// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID           interface{}
	StartTime    time.Time
	EndTime      sql.NullTime
	Duration     sql.NullInt64
	ActivityName string
	Description  string
	Project      string
	Notes        string
}
